name: Release PHP and Nuxt Projects

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up PHP and Composer
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer

      - name: Install PHP dependencies
        run: composer install

      # Set up Node.js and build Nuxt project
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Nuxt dependencies
        run: |
          cd event-viewer
          npm install

      - name: Generate Nuxt site
        run: |
          cd event-viewer
          npm run generate

      - name: Create release artifacts
        run: |
          cd event-viewer
          zip -r generated-site.zip dist
          zip -r php-project.zip .

      - name: Upload release artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: event-viewer/generated-site.zip
          asset_name: generated-site.zip
          asset_content_type: application/zip

      - name: Upload PHP project
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: php-project.zip
          asset_name: php-project.zip
          asset_content_type: application/zip
